run:
  go: "1.22.11"
  timeout: 5m
  tests: false # exclude test from linting

linters:
  disable-all: true
  enable:
    - errcheck
    - revive
    - ineffassign
    - unconvert
    - misspell
    - goimports
    - govet
    - stylecheck
    - typecheck
    - misspell
    # - prealloc not really useful imo
    - dogsled
    - goconst
    - bodyclose
    - unconvert
    - unused
    - gci
    - gofmt
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 11
  errcheck:
    exclude-functions:
      - fmt:.*
      - io/ioutil:^Read.*,
      - github.com/spf13/cobra:MarkFlagRequired
      - github.com/spf13/viper:BindPFlag
  exhaustive:
    check-generated: false
  gci:
    # Gci controls Go package import order and makes it always deterministic
    # https://golangci-lint.run/usage/linters/#gci
    sections:
      - standard
      - default
      - prefix(github.com/zeta-chain/go-tss)
    skip-generated: true

issues:
  exclude-generated: strict
  exclude:
    - composite
  exclude-dirs: [ ".git", ".github" ]