// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signature_notifier.proto

package messages

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeysignSignature struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeysignSignature) Reset()         { *m = KeysignSignature{} }
func (m *KeysignSignature) String() string { return proto.CompactTextString(m) }
func (*KeysignSignature) ProtoMessage()    {}
func (*KeysignSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_7604b65b7d1ea1e3, []int{0}
}

func (m *KeysignSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeysignSignature.Unmarshal(m, b)
}

func (m *KeysignSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeysignSignature.Marshal(b, m, deterministic)
}

func (m *KeysignSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeysignSignature.Merge(m, src)
}

func (m *KeysignSignature) XXX_Size() int {
	return xxx_messageInfo_KeysignSignature.Size(m)
}

func (m *KeysignSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_KeysignSignature.DiscardUnknown(m)
}

var xxx_messageInfo_KeysignSignature proto.InternalMessageInfo

func (m *KeysignSignature) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *KeysignSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*KeysignSignature)(nil), "messages.KeysignSignature")
}

func init() { proto.RegisterFile("signature_notifier.proto", fileDescriptor_7604b65b7d1ea1e3) }

var fileDescriptor_7604b65b7d1ea1e3 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0xce, 0x4c, 0xcf,
	0x4b, 0x2c, 0x29, 0x2d, 0x4a, 0x8d, 0xcf, 0xcb, 0x2f, 0xc9, 0x4c, 0xcb, 0x4c, 0x2d, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0x56, 0x72,
	0xe0, 0x12, 0xf0, 0x4e, 0xad, 0x04, 0x29, 0x0c, 0x86, 0x29, 0x16, 0xe2, 0xe3, 0x62, 0xf2, 0x74,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xf2, 0x74, 0x11, 0x92, 0xe1, 0xe2, 0x84, 0x4b,
	0x4a, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x04, 0x21, 0x04, 0x92, 0xd8, 0xc0, 0x46, 0x1a, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x81, 0xdd, 0xac, 0x43, 0x6e, 0x00, 0x00, 0x00,
}
